name: Integration
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Create secret files
      shell: bash
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      run: |
        mkdir env
        echo "$CLIENT_ID" >> ./env/CLIENT_ID
        echo "$CLIENT_SECRET" >> ./env/CLIENT_SECRET
    - uses: actions/checkout@v2
    - run: cargo test --all
